"""remove_job_id_field_in_jobs_table

Revision ID: 0e1cb93c0946
Revises: 3281aa70cc6b
Create Date: 2024-12-03 18:25:46.176075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0e1cb93c0946'
down_revision: Union[str, None] = '3281aa70cc6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'job_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_id', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
