"""add_job_analysis_table

Revision ID: 3281aa70cc6b
Revises: 8a87b2220639
Create Date: 2024-12-02 17:01:32.978741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3281aa70cc6b'
down_revision: Union[str, None] = '8a87b2220639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_analyses',
    sa.Column('id', sa.String(64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('job_id', sa.String(64), nullable=False),
    sa.Column('status', sa.String(32), nullable=False),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_fixed', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(16), nullable=True),
    sa.Column('skill_tags', sa.Text(), nullable=True),
    sa.Column('experience_level', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_job_analyses_status'), 'job_analyses', ['status'], unique=False)
    op.drop_column('jobs', 'skill_tags')
    op.drop_column('jobs', 'salary_range')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('salary_range', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('jobs', sa.Column('skill_tags', mysql.TEXT(), nullable=True))
    op.drop_index(op.f('ix_job_analyses_status'), table_name='job_analyses')
    op.drop_table('job_analyses')
    # ### end Alembic commands ###
