"""Add locations field in JobAnalysis table

Revision ID: 44db2e037a24
Revises: 422860784587
Create Date: 2025-01-13 16:27:09.682333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44db2e037a24'
down_revision: Union[str, None] = '422860784587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_analyses', sa.Column('locations', sa.Text(), nullable=True, comment="Formatted locations string in 'City, State, Country' format, separated by semicolons"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_analyses', 'locations')
    # ### end Alembic commands ###
