"""add_cascading_delete_to_job

Revision ID: b8c20f62d185
Revises: 0e1cb93c0946
Create Date: 2024-12-05 14:42:51.564929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c20f62d185'
down_revision: Union[str, None] = '0e1cb93c0946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('job_analyses_ibfk_1', 'job_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'job_analyses', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_analyses', type_='foreignkey')
    op.create_foreign_key('job_analyses_ibfk_1', 'job_analyses', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###
