"""add_salary_period

Revision ID: c10276356e0f
Revises: b8c20f62d185
Create Date: 2024-12-10 11:47:29.578221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c10276356e0f'
down_revision: Union[str, None] = 'b8c20f62d185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_analyses', sa.Column('salary_period', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_analyses', 'salary_period')
    # ### end Alembic commands ###
